### ISSUE TITLE
Add tests that nodes are correctly extracted in FunctionReporter

### ISSUE THREAD

**Issue by jameslamb** [uptake/pkgnet#180]
In `test-FunctionReporter`, we should add tests confirming that `pkgnet` correctly translates package exported namespaces to nodes.

**Comment by bburns632** [comment]
I believe [THIS TEST](https://github.com/UptakeOpenSource/pkgnet/blob/master/tests/testthat/test-functional_structure.R#L41) on `baseballstats` confirms that a node is created for each function within the package.  

However, if someone has a suggestion on how we can make this testing more robust, especially on edge case R package designs, we're open to them.

**Comment by jayqi** [comment]
This issue is maybe too open ended, but I have tests checking the whole extracted network for all three of baseballstats, sartre, and milne. I think this should be good enough, and if we identify new edge cases, we should introduce them to those test packages or as new test packages as needed. 

https://github.com/UptakeOpenSource/pkgnet/pull/181/files#diff-672ae504c307217ca3f5678b6473fdd6
