### ISSUE TITLE
feature request - "unique successors" column

### ISSUE THREAD

**Issue by mattdzugan** [uptake/pkgnet#229]
would be cool to also print a column that describes "how many packages would you remove if you removed me"

it would always be `>=1` but would involve calculating how many of your successors are unique to you

**Comment by bburns632** [comment]
@mattdzugan , in other words, how many packages are added to the dependency network just because of this one node, right? 

Sounds like a recurse of the network like this: 

1. Who are my dependencies (out degree neighbors)? 
2. For each neighbor, is my inDegree == 1?  If yes, record and loop back to step 1.

**Comment by bburns632** [comment]
This might also be a variation of [vertex connectivity](https://igraph.org/r/doc/vertex_connectivity.html)

**Comment by bburns632** [comment]
The reverse of this could also be interesting: "I want to remove this recursive dependency.  How many which higher level packages that use this dependency must I cut/modify in order to drop that dependency?"  I believe this is a minimum cut problem.
